sonar.projectKey=mg-gadgets
sonar.projectName=MG-Gadgets

sonar.sources=apps/consumer-ssr

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/*.test.*,**/*.spec.**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
