---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Upgrade installed packages
  apt:
    upgrade: dist
  become: true

- name: Install common packages
  apt:
    name:
      - git
      - curl
      - wget
      - unzip
      - vim
      - tree
      - zip
      - jq
      - gnupg
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - python3-pip
    state: present
  become: true
