apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mg-devops

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: 149828426205.dkr.ecr.us-east-1.amazonaws.com/mg-devops-dev-ecr
    newTag: "23"
