pipeline {
    agent any

    environment {
        IMAGE_NAME = "mg-consumer-ssr"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Workspace') {
            steps {
                sh '''
                pwd
                ls -la
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('apps/consumer-ssr') {
                    sh '''
                    docker build \
                    -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('List Images') {
            steps {
                sh 'docker images'
            }
        }
    }
}
