pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    environment {
        GIT_REPO = "https://github.com/prvzzz/MG-Gadgets.git"
        GIT_BRANCH = "main"
        GIT_CREDENTIALS = "github-pat"
        AWS_REGION = "us-east-1"
        ECR_REPOSITORY = "mg-devops-dev-ecr"
        IMAGE_NAME = "mg-consumer-ssr"
        IMAGE_TAG = "${BUILD_NUMBER}"
        ECR_IMAGE = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}"
        AWS_ACCOUNT_ID = "149828426205"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
                sh '''
                    git checkout ${GIT_BRANCH}
                '''
            }
        }

        stage('Verify Workspace') {
            steps {
                sh '''
                    pwd
                    ls -la
                    ls -la apps
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('apps/consumer-ssr') {
                    sh '''
                        docker build \
                        -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Verify Docker Image') {
            steps {
                sh '''
                    docker images | grep ${IMAGE_NAME}
                '''
            }
        }

        stage('Configure Git') {
            steps {
                sh '''
                    git config --global user.name "Jenkins CI"
                    git config --global user.email "jenkins@mggadgets.com"
                '''
            }
        }

        stage('Login to Amazon ECR') {
            steps {
                sh '''
                     aws ecr get-login-password \
                     --region ${AWS_REGION} | docker login \
                     --username AWS \
                     --password-stdin \
                  ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                  '''
             }
        }
        stage('Push Image to Amazon ECR') {
            steps {
                sh '''
                docker tag ${IMAGE_NAME}:${IMAGE_TAG} \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}

                docker push \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
                '''
             }
        }

        stage('Update Kustomization') {
            steps {
                dir('infra/k8s') {
                    sh '''
                        sed -i 's/newTag:.*/newTag: "'${IMAGE_TAG}'"/' kustomization.yaml

                        echo "Updated kustomization.yaml"

                        cat kustomization.yaml
                    '''
                }
            }
        }

        stage('Debug Git Branch') {
                steps {
                    sh '''
                        git status
                        git branch -a
                        git rev-parse --abbrev-ref HEAD
                    '''
                }
            }

        stage('Commit and Push GitOps Changes') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: "${GIT_CREDENTIALS}",
                    usernameVariable: 'GIT_USERNAME',
                    passwordVariable: 'GIT_TOKEN'
                )]) {
                    sh '''
                        git add infra/k8s/kustomization.yaml

                        git diff --cached --quiet || git commit -m "Update image to ${IMAGE_TAG}"

                        git remote set-url origin https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/prvzzz/MG-Gadgets.git

                        git push origin ${GIT_BRANCH}
                    '''
                }
            }
        }
    }
    

    post {
        success {
            echo 'Pipeline completed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}
