pipeline {
    agent any

    tools {
        sonarQubeScanner 'sonar-scanner'
    }

    options {
        skipDefaultCheckout(true)
    }

    environment {
        GIT_REPO = "https://github.com/prvzzz/MG-Gadgets.git"
        GIT_BRANCH = "main"
        GIT_CREDENTIALS = "github-pat"

        AWS_REGION = "us-east-1"
        AWS_ACCOUNT_ID = "149828426205"

        ECR_REPOSITORY = "mg-devops-dev-ecr"
        IMAGE_NAME = "mg-consumer-ssr"
        IMAGE_TAG = "${BUILD_NUMBER}"
        ECR_IMAGE = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}"
    }

    stages {

        stage('Checkout') {
            steps {
                deleteDir()

                git(
                    branch: "${GIT_BRANCH}",
                    credentialsId: "${GIT_CREDENTIALS}",
                    url: "${GIT_REPO}"
                )
            }
        }

        stage('Skip Jenkins Commit') {
            steps {
                script {
                    def commitMessage = sh(
                        script: 'git log -1 --pretty=%B',
                        returnStdout: true
                    ).trim()

                    echo "Latest Commit: ${commitMessage}"

                    if (commitMessage.contains('[skip ci]')) {
                        currentBuild.result = 'NOT_BUILT'
                        error('Skipping Jenkins generated commit.')
                    }
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    dir('apps/consumer-ssr') {
                        sh '''
                            sonar-scanner \
                              -Dsonar.projectKey=mg-gadgets \
                              -Dsonar.projectName=MG-Gadgets \
                              -Dsonar.sources=. \
                              -Dsonar.sourceEncoding=UTF-8
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Verify Workspace') {
            steps {
                sh '''
                    pwd
                    ls -la
                    ls -la apps
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('apps/consumer-ssr') {
                    sh '''
                        docker build \
                          -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Verify Docker Image') {
            steps {
                sh '''
                    docker images | grep ${IMAGE_NAME}
                '''
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh '''
                    trivy image \
                      --scanners vuln \
                      --severity HIGH,CRITICAL \
                      --format table \
                      --output trivy-report.txt \
                      --exit-code 0 \
                      --no-progress \
                      --skip-version-check \
                      ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }

            post {
                always {
                    archiveArtifacts artifacts: 'trivy-report.txt', fingerprint: true
                }
            }
        }

        stage('Configure Git') {
            steps {
                sh '''
                    git config --global user.name "Jenkins CI"
                    git config --global user.email "jenkins@mggadgets.com"
                '''
            }
        }

        stage('Login to Amazon ECR') {
            steps {
                sh '''
                    aws ecr get-login-password \
                    --region ${AWS_REGION} | docker login \
                    --username AWS \
                    --password-stdin \
                    ${ECR_IMAGE}
                '''
            }
        }

        stage('Push Image to Amazon ECR') {
            steps {
                sh '''
                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_IMAGE}:${IMAGE_TAG}

                    docker push ${ECR_IMAGE}:${IMAGE_TAG}
                '''
            }
        }

        stage('Update Kustomization') {
            steps {
                dir('infra/k8s') {
                    sh '''
                        sed -i 's/newTag:.*/newTag: "'${IMAGE_TAG}'"/' kustomization.yaml

                        echo "Updated kustomization.yaml"

                        cat kustomization.yaml
                    '''
                }
            }
        }

        stage('Commit and Push GitOps Changes') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: "${GIT_CREDENTIALS}",
                        usernameVariable: 'GIT_USERNAME',
                        passwordVariable: 'GIT_TOKEN'
                    )
                ]) {
                    sh '''
                        git add infra/k8s/kustomization.yaml

                        if git diff --cached --quiet; then
                            echo "No changes to commit."
                            exit 0
                        fi

                        git commit -m "[skip ci] Update image to ${IMAGE_TAG}"

                        git remote set-url origin https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/prvzzz/MG-Gadgets.git

                        git push origin HEAD:${GIT_BRANCH}
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }

        always {
            cleanWs()
        }
    }
}